# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_world.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello_world.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11hello_world.proto\x12\x04test\")\n\x0cHelloGrpcReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\" \n\x0eHelloGrpcReply\x12\x0e\n\x06result\x18\x01 \x01(\t2D\n\nHelloWorld\x12\x36\n\x08show_msg\x12\x12.test.HelloGrpcReq\x1a\x14.test.HelloGrpcReply\"\x00\x62\x06proto3'
)




_HELLOGRPCREQ = _descriptor.Descriptor(
  name='HelloGrpcReq',
  full_name='test.HelloGrpcReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='test.HelloGrpcReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='test.HelloGrpcReq.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=68,
)


_HELLOGRPCREPLY = _descriptor.Descriptor(
  name='HelloGrpcReply',
  full_name='test.HelloGrpcReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='test.HelloGrpcReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['HelloGrpcReq'] = _HELLOGRPCREQ
DESCRIPTOR.message_types_by_name['HelloGrpcReply'] = _HELLOGRPCREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloGrpcReq = _reflection.GeneratedProtocolMessageType('HelloGrpcReq', (_message.Message,), {
  'DESCRIPTOR' : _HELLOGRPCREQ,
  '__module__' : 'hello_world_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloGrpcReq)
  })
_sym_db.RegisterMessage(HelloGrpcReq)

HelloGrpcReply = _reflection.GeneratedProtocolMessageType('HelloGrpcReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOGRPCREPLY,
  '__module__' : 'hello_world_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloGrpcReply)
  })
_sym_db.RegisterMessage(HelloGrpcReply)



_HELLOWORLD = _descriptor.ServiceDescriptor(
  name='HelloWorld',
  full_name='test.HelloWorld',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=104,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='show_msg',
    full_name='test.HelloWorld.show_msg',
    index=0,
    containing_service=None,
    input_type=_HELLOGRPCREQ,
    output_type=_HELLOGRPCREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOWORLD)

DESCRIPTOR.services_by_name['HelloWorld'] = _HELLOWORLD

# @@protoc_insertion_point(module_scope)
